In [2]:
import glob
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import seaborn as sns
import seaborn as sb
from config import gkey

gmaps.configure(api_key=gkey)

In [3]:
csv_file = '../Resources/0-200.csv'
car_data1 = pd.read_csv(csv_file)
car_data1 = car_data1.drop(columns=['Stock number:', 
                                    'Unnamed: 0'])
car_data1.head()

,Make:,Model:,Year:,Body type:,Exterior color:,Interior color:,Mileage:,VIN:,Price:,Dealer Name:,Dealer Address:,Trim:
0,Ford,Bronco,2022,SUV / crossover,Race Red,Red (Pv),15 mi,1FMDE5CP9NLB31549,"$51,895",SouthWest Ford,"3000 Fort Worth Hwy Weatherford, TX 76087",NaN
1,Ford,Bronco,2022,SUV / crossover,CACTUS GRAY,STONE/BLACK,0 mi,1FMEE5DP8NLB35076,"$32,219",DeMontrond Ford,"3944 US 59 S Cleveland, TX 77328",NaN
2,Ford,Bronco,2022,SUV / crossover,Blue (Area 51),CLOTH SANDSTONE/BLK SEATS BLACK ONYX INTERIOR,0 mi,1FMDE5AH3NLB11244,"$37,800",Westway Ford,"801 W. Airport Fwy. Irving, TX 75062",Big Bend 2-Door 4WD
3,Ford,Bronco,2022,SUV / crossover,Blue (AREA 51),GRAY/BLACK,0 mi,1FMDE5BH9NLB12171,"$40,669",DeMontrond Ford,"3944 US 59 S Cleveland, TX 77328",NaN
4,Ford,Bronco,2022,SUV / crossover,HOT Pepper Red MET Tint,Dark Space Gray,0 mi,1FMDE5BH2NLA84536,"$41,905",Grand Prairie Ford,"701 E. Palace Parkway Grand Prairie, TX 75050",Big Bend 4-Door 4WD

In [4]:
len(car_data1)

158

In [5]:
csv_file = '../Resources/200-400.csv'
car_data2 = pd.read_csv(csv_file)
car_data2 = car_data2.drop(columns=['Stock number:', 
                                    'Unnamed: 0'])
car_data2.head()

,Make:,Model:,Year:,Trim:,Body type:,Exterior color:,Interior color:,Mileage:,VIN:,Price:,Dealer Name:,Dealer Address:
0,Jeep,Wrangler,2022,Sport 4WD,SUV / crossover,Black Clearcoat,Black,2 mi,1C4GJXAN8NW223826,"$41,305",Freestone Autoplex,"1201 Hwy 84 West Fairfield, TX 75840"
1,Jeep,Wrangler,2022,Sport 4WD,SUV / crossover,Firecracker Red Clearcoat,Black,2 mi,1C4GJXAN1NW223828,"$41,442",Freestone Autoplex,"1201 Hwy 84 West Fairfield, TX 75840"
2,Jeep,Wrangler,2022,Willys 4WD,SUV / crossover,Bright White,Black,0 mi,1C4GJXAN2NW186076,"$42,065",Richardson Chrysler Jeep Dodge Ram,"1321 N Central Expy Richardson, TX 75080"
3,Jeep,Wrangler,2022,Willys 4WD,SUV / crossover,Sarge Green Clearcoat,Black,4 mi,1C4GJXAG3NW268061,"$42,555",Moritz Chrysler Jeep Dodge,"9101 Camp Bowie West Fort Worth, TX 76116"
4,Jeep,Wrangler,2022,Willys 4WD,SUV / crossover,Sting-Gray,Black,0 mi,1C4GJXAN4NW186077,"$42,560",Richardson Chrysler Jeep Dodge Ram,"1321 N Central Expy Richardson, TX 75080"

In [6]:
len(car_data2)

187

In [7]:
csv_file = '../Resources/400-600.csv'
car_data3 = pd.read_csv(csv_file)
car_data3 = car_data3.drop(columns=['Stock number:', 
                                    'Unnamed: 0'])
car_data3.head()

,Make:,Model:,Year:,Trim:,Body type:,Exterior color:,Interior color:,Mileage:,VIN:,Price:,Dealer Name:,Dealer Address:
0,Jeep,Wrangler,2022,Sahara 4WD,SUV / crossover,Bright White Clearcoat,Black,4 mi,1C4HJXEGXNW236822,"$56,305",Pegasus CDJR,"305 South Interstate Highway 45 Ennis, TX 75119"
1,Jeep,Wrangler,2022,Sahara Altitude 4WD,SUV / crossover,Gray,Black,4 mi,1C4HJXEN0NW208154,"$56,575",Frisco Chrysler Dodge Jeep Ram,"9640 State Highway 121 Frisco, TX 75035"
2,Jeep,Wrangler,2022,Sport S 4WD,SUV / crossover,Sarge Green Clearcoat,Black,1 mi,1C4HJXDGXNW176400,"$56,625",Clay Cooley Chrysler Dodge Jeep,"1261 E Airport Fwy Irving, TX 75062"
3,Jeep,Wrangler,2022,NaN,SUV / crossover,Bright White Clearcoat,Black,NaN,1C4HJXDG5NW260009,"$56,690",Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018"
4,Jeep,Wrangler,2022,NaN,SUV / crossover,Hydro Blue Pearl Coat,Black,12 mi,1C4HJXDG2NW254538,"$56,960",Clay Cooley Chrysler Dodge Jeep,"1261 E Airport Fwy Irving, TX 75062"

In [8]:
len(car_data3)

182

In [9]:
csv_file = '../Resources/600-800.csv'
car_data4 = pd.read_csv(csv_file)
car_data4 = car_data4.drop(columns=['Stock #:', 
                                    'Unnamed: 0',
                                    'Delivery:', 
                                    'Price + Delivery:'])
car_data4.head()

,Dealer's Price:,MSRP:,Location:,Mileage:,Transmission:,Exterior Color:,Interior Color:,Est. Gas Mileage*:,Battery Performance:,Engine:,Drivetrain:,Fuel Type:,VIN:,Condition:,Price:,Model:,Dealer Name:,Dealer Address:,Cabin Size:,NHTSA Overall Safety Rating:
0,"$67,935","$67,935","Lamesa, TX\n279 mi away",15 miles,8-Speed Automatic,Bright White Clearcoat,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,1C4JJXR61NW152861,New,"$68,218",Wrangler,Premier CDJR of Lamesa,"1611 Lubbock Hwy Lamesa, TX 79331",NaN,NaN
1,"$69,920","$69,920","Prosper, TX\n35 mi away",---,8-Speed Automatic,Sting-Gray Clearcoat,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,1C4JJXR64NW108322,New,"$69,920",Wrangler,Shottenkirk Prosper Chrysler Dodge Jeep Ram,"2550 W University Dr Prosper, TX 75078",NaN,NaN
2,"$68,090","$70,225","Lake Charles, LA\n294 mi away",---,8-Speed Automatic,Sting-Gray Clearcoat,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,1C4JJXR66NW214819,New,"$68,539",Wrangler,Mark Dodge,"3777 Gerstner Memorial Blvd Lake Charles, LA 7...",NaN,NaN
3,"$68,700","$68,700","Ennis, TX\n43 mi away",3 miles,8-Speed Automatic,Black Clearcoat,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,1C4JJXR6XNW108101,New,"$68,700",Wrangler,Pegasus CDJR,"305 South Interstate Highway 45 Ennis, TX 75119",NaN,NaN
4,"$68,287","$70,445","Lake Charles, LA\n294 mi away",---,8-Speed Automatic,Sarge Green Clearcoat,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,1C4JJXR6XNW239562,New,"$68,736",Wrangler,Mark Dodge,"3777 Gerstner Memorial Blvd Lake Charles, LA 7...",NaN,NaN

In [10]:
len(car_data4)

140

In [11]:
csv_file = '../Resources/800-1000.csv'
car_data5 = pd.read_csv(csv_file)
car_data5 = car_data5.drop(columns=['Stock #:', 
                                    'Unnamed: 0',
                                    'Delivery:', 
                                    'Price + Delivery:'])
car_data5.head()

,Dealer's Price:,MSRP:,Location:,Mileage:,Transmission:,Exterior Color:,Interior Color:,Est. Gas Mileage*:,Engine:,Drivetrain:,Fuel Type:,VIN:,Condition:,Price:,Model:,Dealer Name:,Dealer Address:,Battery Performance:,Cabin Size:
0,"$39,615","$42,715","Houston, TX\n172 mi away",0 miles,8-Speed Automatic,Brown (Limited Edition Gobi),Black,21 MPG City\n24 MPG Highway\n22 MPG Combined,270 hp 2L I4,Four-Wheel Drive,Gasoline,1C4HJXDN1NW243593,New,"$39,615",Wrangler,Mac Haik Chrysler Dodge Jeep RAM Energy Corridor,"12111 Katy Fwy Houston, TX 77079",NaN,NaN
1,"$39,665","$42,765","Houston, TX\n172 mi away",0 miles,8-Speed Automatic,Sarge Green,Black,21 MPG City\n24 MPG Highway\n22 MPG Combined,270 hp 2L I4,Four-Wheel Drive,Gasoline,1C4HJXDNXNW252227,New,"$39,665",Wrangler,Mac Haik Chrysler Dodge Jeep RAM Energy Corridor,"12111 Katy Fwy Houston, TX 77079",NaN,NaN
2,"$41,609","$42,765","Houston, TX\n172 mi away",1 miles,8-Speed Automatic,Sarge Green,Brown (Heritage Tan/Black),21 MPG City\n24 MPG Highway\n22 MPG Combined,270 hp 2L I4,Four-Wheel Drive,Gasoline,1C4HJXDN3NW252232,New,"$41,609",Wrangler,Mac Haik Chrysler Dodge Jeep RAM Energy Corridor,"12111 Katy Fwy Houston, TX 77079",NaN,NaN
3,"$39,885","$42,985","Houston, TX\n172 mi away",0 miles,8-Speed Automatic,Black,Brown (Heritage Tan/Black),18 MPG City\n23 MPG Highway\n20 MPG Combined,285 hp 3.6L V6,Four-Wheel Drive,Gasoline,1C4HJXDG1NW240629,New,"$39,885",Wrangler,Mac Haik Chrysler Dodge Jeep RAM Energy Corridor,"12111 Katy Fwy Houston, TX 77079",NaN,NaN
4,"$39,965","$43,065","Houston, TX\n172 mi away",0 miles,8-Speed Automatic,Sarge Green,Black,21 MPG City\n24 MPG Highway\n22 MPG Combined,270 hp 2L I4,Four-Wheel Drive,Gasoline,1C4HJXDN5NW243595,New,"$39,965",Wrangler,Mac Haik Chrysler Dodge Jeep RAM Energy Corridor,"12111 Katy Fwy Houston, TX 77079",NaN,NaN

In [12]:
len(car_data5)

167

In [13]:
csv_file = '../Resources/1000-1200.csv'
car_data6 = pd.read_csv(csv_file)
car_data6 = car_data6.drop(columns=['Stock #:', 
                                    'Unnamed: 0',
                                    'Delivery:', 
                                    'Price + Delivery:'])
car_data6.head()

,Dealer's Price:,MSRP:,Location:,Mileage:,Transmission:,Exterior Color:,Interior Color:,Est. Gas Mileage*:,Engine:,Drivetrain:,Fuel Type:,Cabin Size:,VIN:,Condition:,Price:,Model:,Dealer Name:,Dealer Address:,Battery Performance:,NHTSA Overall Safety Rating:
0,"$50,453",Not Provided,"Boerne, TX\n25 mi away",---,Automatic,Gray,Black (Blk Fabric),17 MPG City\n23 MPG Highway\n19 MPG Combined,389 hp 3.5L V6,Four-Wheel Drive,Gasoline,Large Crew Cab,5TFLA5DB5NX038535,New,"$50,453",Tundra,Toyota of Boerne,"31205 I-10 W<br>Boerne, TX 78006",NaN,NaN
1,"$54,796","$54,796","San Antonio, TX\n8 mi away",0 miles,Automatic,Black,NaN,18 MPG City\n24 MPG Highway\n20 MPG Combined,389 hp 3.5L V6,4X2,Gasoline,Large Crew Cab,5TFJA5AB4NX010771,New,"$54,796",Tundra,Alamo Toyota,"18019 US 281 North<br>San Antonio, TX 78232",NaN,NaN
2,"$55,317","$55,317","San Antonio, TX\n10 mi away",10 miles,Automatic,Magnetic Gray,Gray (GRAPHITE),17 MPG City\n23 MPG Highway\n19 MPG Combined,389 hp 3.5L V6,Four-Wheel Drive,Gasoline,Large Crew Cab,5TFLA5DB3NX040445,New,"$55,317",Tundra,North Park Toyota of San Antonio,"10703 S.W. Loop 410<br>San Antonio, TX 78211",NaN,NaN
3,"$58,469","$58,469","San Antonio, TX\n8 mi away",0 miles,Automatic,Blue,NaN,18 MPG City\n24 MPG Highway\n20 MPG Combined,437 hp 3.5L V6 Hybrid,4X2,Hybrid,Large Crew Cab,5TFJC5BC7NX001029,New,"$58,469",Tundra,Alamo Toyota,"18019 US 281 North<br>San Antonio, TX 78232",NaN,NaN
4,"$58,640","$58,640","Laredo, TX\n145 mi away",0 miles,Automatic,Silver (MIDNIGHT-BLACK METALLIC),NaN,18 MPG City\n24 MPG Highway\n20 MPG Combined,437 hp 3.5L V6 Hybrid,4X2,Hybrid,Large Crew Cab,5TFJC5AB0NX001141,New,"$58,859",Tundra,Toyota of Laredo,"6324 Bob Bullock Loop<br>Laredo, TX 78041",NaN,NaN

In [14]:
len(car_data6)

145

In [15]:
csv_file = '../Resources/1200-1400.csv'
car_data7 = pd.read_csv(csv_file)
car_data7 = car_data7.drop(columns=['Stock number:', 
                                    'Unnamed: 0'])
car_data7.head()

,Make:,Model:,Year:,Trim:,Body type:,Exterior color:,Interior color:,Mileage:,VIN:,Price:,Dealer Name:,Dealer Address:
0,Jeep,Wrangler,2022,Sport 4WD,SUV / crossover,Brown (Limited Edition Gobi Clearcoat),Black,0 mi,1C4HJXDN6NW243959,"$40,359",San Antonio Dodge Chrysler Jeep Ram,"11910 N Ih 35<br>San Antonio, TX 78233"
1,Jeep,Wrangler,2022,Willys 4WD,SUV / crossover,Bright White,Black,0 mi,1C4HJXDNXNW253569,"$42,125",Mac Haik Chrysler Dodge Jeep RAM Energy Corridor,"12111 Katy Fwy<br>Houston, TX 77079"
2,Jeep,Wrangler,2022,Sport Altitude 4WD,SUV / crossover,Gray,Black,0 mi,1C4HJXDN8NW242280,"$43,379",Frisco Chrysler Dodge Jeep Ram,"9640 State Highway 121<br>Frisco, TX 75035"
3,Jeep,Wrangler,2022,Sport Altitude 4WD,SUV / crossover,Black,Black,0 mi,1C4HJXDG9NW226056,"$43,879",Frisco Chrysler Dodge Jeep Ram,"9640 State Highway 121<br>Frisco, TX 75035"
4,Jeep,Wrangler,2022,Sport S 4WD,SUV / crossover,Sting-Gray Clearcoat,Black,7 mi,1C4HJXDG8NW241924,"$44,575",Covert Chrysler Dodge Jeep Ram-Austin,"8107 Research Blvd<br>Austin, TX 78758"

In [16]:
len(car_data7)

170

In [17]:
csv_file = '../Resources/1400-1600.csv'
car_data8 = pd.read_csv(csv_file)
car_data8 = car_data8.drop(columns=['Stock number:', 
                                    'Unnamed: 0'])
car_data8.head()

,Make:,Model:,Year:,Trim:,Body type:,Exterior color:,Interior color:,Mileage:,VIN:,Price:,Dealer Name:,Dealer Address:
0,Jeep,Wrangler,2022,Rubicon 4WD,SUV / crossover,Bright White Clearcoat,Black,15 mi,1C4JJXR61NW152861,"$68,237",Premier CDJR of Lamesa,"1611 Lubbock Hwy Lamesa, TX 79331"
1,Jeep,Wrangler,2022,Rubicon 4WD,SUV / crossover,Sting-Gray Clearcoat,Black,NaN,1C4JJXR66NW214819,"$68,501",Mark Dodge,"3777 Gerstner Memorial Blvd Lake Charles, LA 7..."
2,Jeep,Wrangler,2022,Rubicon 4WD,SUV / crossover,Sarge Green Clearcoat,Black,NaN,1C4JJXR6XNW239562,"$68,698",Mark Dodge,"3777 Gerstner Memorial Blvd Lake Charles, LA 7..."
3,Jeep,Wrangler,2022,Rubicon 4WD,SUV / crossover,Black Clearcoat,Black,NaN,1C4JJXR6XNW245653,"$68,856",Mark Dodge,"3777 Gerstner Memorial Blvd Lake Charles, LA 7..."
4,Jeep,Wrangler,2022,Rubicon 4WD,SUV / crossover,Firecracker Red Clearcoat,Black,0 mi,1C4JJXR62NW222268,"$69,884",San Antonio Dodge Chrysler Jeep Ram,"11910 N Ih 35 San Antonio, TX 78233"

In [18]:
len(car_data8)

175

In [19]:
csv_file = '../Resources/1600-1800.csv'
car_data9 = pd.read_csv(csv_file)
car_data9 = car_data9.drop(columns=['Stock number:', 
                                    'Unnamed: 0'])
car_data9.head()

,Make:,Model:,Year:,Trim:,Body type:,Exterior color:,Interior color:,Mileage:,VIN:,Price:,Dealer Name:,Dealer Address:
0,Ford,Bronco,2022,Outer Banks 4-Door 4WD,SUV / crossover,Hot Pepper Red Metallic Tinted Clearcoat,Roast w/Black Onyx,15 mi,1FMEE5BP1NLB31602,4WD,AutoNation Ford Katy,"20777 Katy Fwy<br>Katy, TX 77450"
1,Ford,Maverick,2022,NaN,Coupe,Gray (Cactus Grey),Black Onyx/Dark Slate,0 mi,3FTTW8E99NRA83386,"$23,170",Planet Ford,"20403 I-45 North<br>Spring, TX 77388"
2,Ford,Maverick,2022,NaN,Coupe,Velocity Blue Metallic,Desert Brown,0 mi,3FTTW8F98NRA83751,"$36,970",Planet Ford,"20403 I-45 North<br>Spring, TX 77388"
3,Ford,Maverick,2022,NaN,Coupe,Alto Blue Tinted Clearcoat Metallic,Blue (Navy Pier/Medium Slate),0 mi,3FTTW8E35NRA84790,"$25,095",Planet Ford,"20403 I-45 North<br>Spring, TX 77388"
4,Ford,Maverick,2022,NaN,Coupe,Gray (Cactus Grey),Black Onyx/Dark Slate,0 mi,3FTTW8E32NRA74007,"$21,590",Planet Ford,"20403 I-45 North<br>Spring, TX 77388"

In [20]:
len(car_data9)

167

In [21]:
csv_file = '../Resources/1800-2000.csv'
car_data10 = pd.read_csv(csv_file)
car_data10 = car_data10.drop(columns=['Unnamed: 0'])
car_data10.head()

,Make:,Model:,Year:,Trim:,Body type:,Exterior color:,Interior color:,Mileage:,VIN:,Stock number:,Price:,Dealer Name:,Dealer Address:
0,Jeep,Wrangler,2022,Sport S 4WD,SUV / crossover,Gray (Granite Crystal Metallic Clearcoat),Black,5 mi,1C4HJXDN8NW204340,NW204340,"$44,030",Southfork Chrysler Dodge Jeep Ram,"17725 South Fwy Manvel, TX 77578"
1,Jeep,Wrangler,2022,Sport Altitude 4WD,SUV / crossover,Black Clearcoat,Black,0 mi,1C4HJXDN6NW211996,NW211996,"$44,325",River Oaks Chrysler Jeep Dodge Ram,"4807 Kirby Drive Houston, TX 77098"
2,Jeep,Wrangler,2022,Sport S 4WD,SUV / crossover,Bright White Clearcoat,Black,20 mi,1C4HJXDGXNW180141,52081768,"$44,530",Momentum Chrysler Dodge Jeep Ram,"3704 NE I 10 Frontage Rd Sealy, TX 77474"
3,Jeep,Wrangler,2022,Sport Altitude 4WD,SUV / crossover,Firecracker Red Clearcoat,Black,0 mi,1C4HJXDNXNW190912,NW190912,"$44,670",River Oaks Chrysler Jeep Dodge Ram,"4807 Kirby Drive Houston, TX 77098"
4,Jeep,Wrangler,2022,Willys 4WD,SUV / crossover,Bright White Clearcoat,Black,0 mi,1C4HJXDG6NW257619,NW257619,"$44,680",River Oaks Chrysler Jeep Dodge Ram,"4807 Kirby Drive Houston, TX 77098"

In [22]:
len(car_data10)

179

In [23]:
csv_file = '../Resources/2000-2221.csv'
car_data11 = pd.read_csv(csv_file)
car_data11 = car_data11.drop(columns=['Stock #:', 
                                      'Unnamed: 0',
                                      'Delivery:', 
                                      'Price + Delivery:'])
car_data11

,Dealer's Price:,MSRP:,Location:,Mileage:,Transmission:,Exterior Color:,Interior Color:,Est. Gas Mileage*:,Battery Performance:,Engine:,Drivetrain:,Fuel Type:,VIN:,Condition:,Price:,Model:,Dealer Name:,Dealer Address:,Cabin Size:
0,"$54,880","$58,280","Houston, TX\n18 mi away",0 miles,8-Speed Automatic,Sting-Gray,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,1C4JJXP64NW275797,New,"$54,880",Wrangler,Mac Haik Chrysler Dodge Jeep RAM Energy Corridor,"12111 Katy Fwy<br>Houston, TX 77079",NaN
1,"$54,880","$58,280","Houston, TX\n18 mi away",0 miles,8-Speed Automatic,Sting-Gray,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,1C4JJXP64NW275797,New,"$54,880",Wrangler,Mac Haik Chrysler Dodge Jeep RAM Energy Corridor,"12111 Katy Fwy<br>Houston, TX 77079",NaN
2,"$54,887","$56,980","Lake Charles, LA\n134 mi away",---,8-Speed Automatic,Bright White Clearcoat,Dark Saddle/Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,1C4JJXP68NW260722,New,"$55,084",Wrangler,Mark Dodge,"3777 Gerstner Memorial Blvd<br>Lake Charles, L...",NaN
3,"$54,973","$57,075","Lake Charles, LA\n134 mi away",---,8-Speed Automatic,Hydro Blue Pearl Coat,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,1C4JJXP65NW239486,New,"$55,170",Wrangler,Mark Dodge,"3777 Gerstner Memorial Blvd<br>Lake Charles, L...",NaN
4,"$54,981","$57,085","Lake Charles, LA\n134 mi away",---,8-Speed Automatic,Bright White Clearcoat,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,1C4JJXP69NW271678,New,"$55,178",Wrangler,Mark Dodge,"3777 Gerstner Memorial Blvd<br>Lake Charles, L...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,"$68,600","$68,600","Conroe, TX\n45 mi away",5 miles,Automatic,NaN,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,5TFPC5DB5NX004915,New,"$68,600",Tundra,Gullo Toyota of Conroe,"500 I-45 South<br>Conroe, TX 77304",Large Crew Cab
172,"$68,748","$67,253","Richmond, TX\n23 mi away",10 miles,Automatic,Supersonic Red,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,389 hp 3.5L V6,Four-Wheel Drive,Gasoline,5TFMA5DB6NX034823,New,"$68,748",Tundra,Sterling McCall Toyota Fort Bend,"20465 Southwest Freeway<br>Richmond, TX 77469",Large Crew Cab
173,"$78,001","$78,001","Conroe, TX\n45 mi away",6 miles,Automatic,NaN,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,5TFVC5DB5NX002511,New,"$78,001",Tundra,Gullo Toyota of Conroe,"500 I-45 South<br>Conroe, TX 77304",Large Crew Cab
174,"$78,426","$78,426","Houston, TX\n5 mi away",---,Automatic,White (Wind Chill Prl),Black (Blk/Wht Semi-Aniline Lth),17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,5TFVC5DB8NX002583,New,"$78,426",Tundra,Mike Calvert Toyota,"2333 South Loop West<br>Houston, TX 77054",Large Crew Cab
175,"$78,990",Not Provided,"Houston, TX\n11 mi away",248 miles,Automatic,Gray,Black,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,389 hp 3.5L V6,Four-Wheel Drive,Gasoline,5TFLA5DB1NX019691,New,"$78,990",Tundra,Mike Calvert Toyota,"2333 South Loop West<br>Houston, TX 77054","Large Crew Cab, Short Bed"

In [24]:
len(car_data11)

176

In [25]:
all_scraping_data = pd.concat([car_data1, car_data2, car_data3, car_data4, 
                          car_data5, car_data6, car_data7, car_data8,
                         car_data9, car_data10, car_data11])
all_scraping_data = all_scraping_data.drop(columns=['Stock number:'])

all_scraping_data.head()

,Make:,Model:,Year:,Body type:,Exterior color:,Interior color:,Mileage:,VIN:,Price:,Dealer Name:,...,Exterior Color:,Interior Color:,Est. Gas Mileage*:,Battery Performance:,Engine:,Drivetrain:,Fuel Type:,Condition:,Cabin Size:,NHTSA Overall Safety Rating:
0,Ford,Bronco,2022.0,SUV / crossover,Race Red,Red (Pv),15 mi,1FMDE5CP9NLB31549,"$51,895",SouthWest Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ford,Bronco,2022.0,SUV / crossover,CACTUS GRAY,STONE/BLACK,0 mi,1FMEE5DP8NLB35076,"$32,219",DeMontrond Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ford,Bronco,2022.0,SUV / crossover,Blue (Area 51),CLOTH SANDSTONE/BLK SEATS BLACK ONYX INTERIOR,0 mi,1FMDE5AH3NLB11244,"$37,800",Westway Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ford,Bronco,2022.0,SUV / crossover,Blue (AREA 51),GRAY/BLACK,0 mi,1FMDE5BH9NLB12171,"$40,669",DeMontrond Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ford,Bronco,2022.0,SUV / crossover,HOT Pepper Red MET Tint,Dark Space Gray,0 mi,1FMDE5BH2NLA84536,"$41,905",Grand Prairie Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
len(all_scraping_data)

1846

In [27]:
all_scraping_data.to_csv('../Resources/all_scraping_data2.csv', index=False)

In [28]:
csv_file = '../Resources/all_scraping_data2.csv'
all_scraping_data2 = pd.read_csv(csv_file)
all_scraping_data2.head()

,Make:,Model:,Year:,Body type:,Exterior color:,Interior color:,Mileage:,VIN:,Price:,Dealer Name:,...,Exterior Color:,Interior Color:,Est. Gas Mileage*:,Battery Performance:,Engine:,Drivetrain:,Fuel Type:,Condition:,Cabin Size:,NHTSA Overall Safety Rating:
0,Ford,Bronco,2022.0,SUV / crossover,Race Red,Red (Pv),15 mi,1FMDE5CP9NLB31549,"$51,895",SouthWest Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ford,Bronco,2022.0,SUV / crossover,CACTUS GRAY,STONE/BLACK,0 mi,1FMEE5DP8NLB35076,"$32,219",DeMontrond Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ford,Bronco,2022.0,SUV / crossover,Blue (Area 51),CLOTH SANDSTONE/BLK SEATS BLACK ONYX INTERIOR,0 mi,1FMDE5AH3NLB11244,"$37,800",Westway Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ford,Bronco,2022.0,SUV / crossover,Blue (AREA 51),GRAY/BLACK,0 mi,1FMDE5BH9NLB12171,"$40,669",DeMontrond Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ford,Bronco,2022.0,SUV / crossover,HOT Pepper Red MET Tint,Dark Space Gray,0 mi,1FMDE5BH2NLA84536,"$41,905",Grand Prairie Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
# rename columns
# all_scraping_data2=all_scraping_data2.replace({
#     "Interior Color:":"Interior Color",
#     "Interior color:":"Interior Color",
    
#     "Exterior Color:":"Exterior Color",
#     "Exterior color:":"Exterior Color",
    
#     "Dealer Address:":"Dealer Address",
#     "Location:":"Dealer Address",
    
#     "Dealer's Price:":"Dealer's Price",
#     "Price:":"Dealer's Price"
# })
# all_scraping_data2.head()

In [30]:
# all_scraping_data2['Address:'] = ""

# for index, row in all_scraping_data2.iterrows():
#     if len(row["Dealer Address:"]) >5:
#         row['Address:'] = row["Dealer Address:"]
#     elif len(row["Location:"]) >5:
#         row['Address:'] = row["Location:"]
# all_scraping_data2.head()

In [31]:
all_scraping_data2.columns

Index(['Make:', 'Model:', 'Year:', 'Body type:', 'Exterior color:',
       'Interior color:', 'Mileage:', 'VIN:', 'Price:', 'Dealer Name:',
       'Dealer Address:', 'Trim:', 'Dealer's Price:', 'MSRP:', 'Location:',
       'Transmission:', 'Exterior Color:', 'Interior Color:',
       'Est. Gas Mileage*:', 'Battery Performance:', 'Engine:', 'Drivetrain:',
       'Fuel Type:', 'Condition:', 'Cabin Size:',
       'NHTSA Overall Safety Rating:'],
      dtype='object')

In [ ]:
# all_scraping_data2['Address:'] = ""

# for index, row in all_scraping_data2.iterrows():
#     if len(row["Dealer Address:"]) != None:
#         row['Address:'] = row["Dealer Address:"]
#     elif len(row["Location:"]) != None:
#         row['Address:'] = row["Location:"]

# all_scraping_data2[['Address:', 'Dealer Address:', "Location:"]]

In [ ]:
# all_scraping_data2['Address:'] = ""

# for index, row in all_scraping_data2.iterrows():
#     if "TX" in row["Dealer Address:"]:
#         row['Address:'] = row["Dealer Address:"]
#     elif "TX" in row["Location:"]:
#         row['Address:'] = row["Location:"]

# all_scraping_data2[['Address:', 'Dealer Address:', "Location:"]]

In [35]:
all_scraping_data2 = all_scraping_data2.loc[all_scraping_data2["Dealer Address:"].str.contains('TX')]
all_scraping_data2.head()

,Make:,Model:,Year:,Body type:,Exterior color:,Interior color:,Mileage:,VIN:,Price:,Dealer Name:,...,Exterior Color:,Interior Color:,Est. Gas Mileage*:,Battery Performance:,Engine:,Drivetrain:,Fuel Type:,Condition:,Cabin Size:,NHTSA Overall Safety Rating:
0,Ford,Bronco,2022.0,SUV / crossover,Race Red,Red (Pv),15 mi,1FMDE5CP9NLB31549,"$51,895",SouthWest Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ford,Bronco,2022.0,SUV / crossover,CACTUS GRAY,STONE/BLACK,0 mi,1FMEE5DP8NLB35076,"$32,219",DeMontrond Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ford,Bronco,2022.0,SUV / crossover,Blue (Area 51),CLOTH SANDSTONE/BLK SEATS BLACK ONYX INTERIOR,0 mi,1FMDE5AH3NLB11244,"$37,800",Westway Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ford,Bronco,2022.0,SUV / crossover,Blue (AREA 51),GRAY/BLACK,0 mi,1FMDE5BH9NLB12171,"$40,669",DeMontrond Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ford,Bronco,2022.0,SUV / crossover,HOT Pepper Red MET Tint,Dark Space Gray,0 mi,1FMDE5BH2NLA84536,"$41,905",Grand Prairie Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
# all_scraping_data2 = all_scraping_data2.drop(columns=[#'Location:',
#                                                      'NHTSA Overall Safety Rating:',
#                                                      'Interior Color:',
#                                                       'Est. Gas Mileage*:',
#                                                       'Battery Performance:',
#                                                       'Engine:',
#                                                       'Drivetrain:',
#                                                       'Fuel Type:',
#                                                       'Condition:',
#                                                       'Cabin Size:',
#                                                       'NHTSA Overall Safety Rating:',
#                                                       'Address:'])
# all_scraping_data2

In [38]:
all_scraping_data3 = all_scraping_data2
all_scraping_data3

,Make:,Model:,Year:,Body type:,Exterior color:,Interior color:,Mileage:,VIN:,Price:,Dealer Name:,...,Exterior Color:,Interior Color:,Est. Gas Mileage*:,Battery Performance:,Engine:,Drivetrain:,Fuel Type:,Condition:,Cabin Size:,NHTSA Overall Safety Rating:
0,Ford,Bronco,2022.0,SUV / crossover,Race Red,Red (Pv),15 mi,1FMDE5CP9NLB31549,"$51,895",SouthWest Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ford,Bronco,2022.0,SUV / crossover,CACTUS GRAY,STONE/BLACK,0 mi,1FMEE5DP8NLB35076,"$32,219",DeMontrond Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ford,Bronco,2022.0,SUV / crossover,Blue (Area 51),CLOTH SANDSTONE/BLK SEATS BLACK ONYX INTERIOR,0 mi,1FMDE5AH3NLB11244,"$37,800",Westway Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ford,Bronco,2022.0,SUV / crossover,Blue (AREA 51),GRAY/BLACK,0 mi,1FMDE5BH9NLB12171,"$40,669",DeMontrond Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ford,Bronco,2022.0,SUV / crossover,HOT Pepper Red MET Tint,Dark Space Gray,0 mi,1FMDE5BH2NLA84536,"$41,905",Grand Prairie Ford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1841,NaN,Tundra,NaN,NaN,NaN,NaN,5 miles,5TFPC5DB5NX004915,"$68,600",Gullo Toyota of Conroe,...,NaN,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,New,Large Crew Cab,NaN
1842,NaN,Tundra,NaN,NaN,NaN,NaN,10 miles,5TFMA5DB6NX034823,"$68,748",Sterling McCall Toyota Fort Bend,...,Supersonic Red,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,389 hp 3.5L V6,Four-Wheel Drive,Gasoline,New,Large Crew Cab,NaN
1843,NaN,Tundra,NaN,NaN,NaN,NaN,6 miles,5TFVC5DB5NX002511,"$78,001",Gullo Toyota of Conroe,...,NaN,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,New,Large Crew Cab,NaN
1844,NaN,Tundra,NaN,NaN,NaN,NaN,---,5TFVC5DB8NX002583,"$78,426",Mike Calvert Toyota,...,White (Wind Chill Prl),Black (Blk/Wht Semi-Aniline Lth),17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,New,Large Crew Cab,NaN
1845,NaN,Tundra,NaN,NaN,NaN,NaN,248 miles,5TFLA5DB1NX019691,"$78,990",Mike Calvert Toyota,...,Gray,Black,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,389 hp 3.5L V6,Four-Wheel Drive,Gasoline,New,"Large Crew Cab, Short Bed",NaN

In [39]:
all_scraping_data3 = all_scraping_data2.dropna(subset=['MSRP:'])
all_scraping_data3

,Make:,Model:,Year:,Body type:,Exterior color:,Interior color:,Mileage:,VIN:,Price:,Dealer Name:,...,Exterior Color:,Interior Color:,Est. Gas Mileage*:,Battery Performance:,Engine:,Drivetrain:,Fuel Type:,Condition:,Cabin Size:,NHTSA Overall Safety Rating:
527,NaN,Wrangler,NaN,NaN,NaN,NaN,15 miles,1C4JJXR61NW152861,"$68,218",Premier CDJR of Lamesa,...,Bright White Clearcoat,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
528,NaN,Wrangler,NaN,NaN,NaN,NaN,---,1C4JJXR64NW108322,"$69,920",Shottenkirk Prosper Chrysler Dodge Jeep Ram,...,Sting-Gray Clearcoat,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
530,NaN,Wrangler,NaN,NaN,NaN,NaN,3 miles,1C4JJXR6XNW108101,"$68,700",Pegasus CDJR,...,Black Clearcoat,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
534,NaN,Wrangler,NaN,NaN,NaN,NaN,---,1C4JJXR62NW270773,"$70,475",Classic Chrysler Dodge Jeep Ram Fiat,...,Bright White Clearcoat,White (Alx9),20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
535,NaN,Wrangler,NaN,NaN,NaN,NaN,---,1C4JJXR61NW274197,"$70,870",Classic Chrysler Dodge Jeep Ram Fiat,...,Sting-Gray Clearcoat,Gray (Alx9),20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1841,NaN,Tundra,NaN,NaN,NaN,NaN,5 miles,5TFPC5DB5NX004915,"$68,600",Gullo Toyota of Conroe,...,NaN,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,New,Large Crew Cab,NaN
1842,NaN,Tundra,NaN,NaN,NaN,NaN,10 miles,5TFMA5DB6NX034823,"$68,748",Sterling McCall Toyota Fort Bend,...,Supersonic Red,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,389 hp 3.5L V6,Four-Wheel Drive,Gasoline,New,Large Crew Cab,NaN
1843,NaN,Tundra,NaN,NaN,NaN,NaN,6 miles,5TFVC5DB5NX002511,"$78,001",Gullo Toyota of Conroe,...,NaN,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,New,Large Crew Cab,NaN
1844,NaN,Tundra,NaN,NaN,NaN,NaN,---,5TFVC5DB8NX002583,"$78,426",Mike Calvert Toyota,...,White (Wind Chill Prl),Black (Blk/Wht Semi-Aniline Lth),17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,New,Large Crew Cab,NaN
1845,NaN,Tundra,NaN,NaN,NaN,NaN,248 miles,5TFLA5DB1NX019691,"$78,990",Mike Calvert Toyota,...,Gray,Black,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,389 hp 3.5L V6,Four-Wheel Drive,Gasoline,New,"Large Crew Cab, Short Bed",NaN

In [40]:
all_scraping_data4 = all_scraping_data3.drop(columns=['Exterior color:',
                                                      'Interior color:',
                                                      'Exterior Color:'])
all_scraping_data4

,Make:,Model:,Year:,Body type:,Mileage:,VIN:,Price:,Dealer Name:,Dealer Address:,Trim:,...,Transmission:,Interior Color:,Est. Gas Mileage*:,Battery Performance:,Engine:,Drivetrain:,Fuel Type:,Condition:,Cabin Size:,NHTSA Overall Safety Rating:
527,NaN,Wrangler,NaN,NaN,15 miles,1C4JJXR61NW152861,"$68,218",Premier CDJR of Lamesa,"1611 Lubbock Hwy Lamesa, TX 79331",NaN,...,8-Speed Automatic,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
528,NaN,Wrangler,NaN,NaN,---,1C4JJXR64NW108322,"$69,920",Shottenkirk Prosper Chrysler Dodge Jeep Ram,"2550 W University Dr Prosper, TX 75078",NaN,...,8-Speed Automatic,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
530,NaN,Wrangler,NaN,NaN,3 miles,1C4JJXR6XNW108101,"$68,700",Pegasus CDJR,"305 South Interstate Highway 45 Ennis, TX 75119",NaN,...,8-Speed Automatic,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
534,NaN,Wrangler,NaN,NaN,---,1C4JJXR62NW270773,"$70,475",Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018",NaN,...,8-Speed Automatic,White (Alx9),20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
535,NaN,Wrangler,NaN,NaN,---,1C4JJXR61NW274197,"$70,870",Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018",NaN,...,8-Speed Automatic,Gray (Alx9),20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1841,NaN,Tundra,NaN,NaN,5 miles,5TFPC5DB5NX004915,"$68,600",Gullo Toyota of Conroe,"500 I-45 South<br>Conroe, TX 77304",NaN,...,Automatic,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,New,Large Crew Cab,NaN
1842,NaN,Tundra,NaN,NaN,10 miles,5TFMA5DB6NX034823,"$68,748",Sterling McCall Toyota Fort Bend,"20465 Southwest Freeway<br>Richmond, TX 77469",NaN,...,Automatic,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,389 hp 3.5L V6,Four-Wheel Drive,Gasoline,New,Large Crew Cab,NaN
1843,NaN,Tundra,NaN,NaN,6 miles,5TFVC5DB5NX002511,"$78,001",Gullo Toyota of Conroe,"500 I-45 South<br>Conroe, TX 77304",NaN,...,Automatic,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,New,Large Crew Cab,NaN
1844,NaN,Tundra,NaN,NaN,---,5TFVC5DB8NX002583,"$78,426",Mike Calvert Toyota,"2333 South Loop West<br>Houston, TX 77054",NaN,...,Automatic,Black (Blk/Wht Semi-Aniline Lth),17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,New,Large Crew Cab,NaN
1845,NaN,Tundra,NaN,NaN,248 miles,5TFLA5DB1NX019691,"$78,990",Mike Calvert Toyota,"2333 South Loop West<br>Houston, TX 77054",NaN,...,Automatic,Black,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,389 hp 3.5L V6,Four-Wheel Drive,Gasoline,New,"Large Crew Cab, Short Bed",NaN

In [41]:
all_scraping_data5 = all_scraping_data4.drop(columns=['Trim:'])
all_scraping_data5

,Make:,Model:,Year:,Body type:,Mileage:,VIN:,Price:,Dealer Name:,Dealer Address:,Dealer's Price:,...,Transmission:,Interior Color:,Est. Gas Mileage*:,Battery Performance:,Engine:,Drivetrain:,Fuel Type:,Condition:,Cabin Size:,NHTSA Overall Safety Rating:
527,NaN,Wrangler,NaN,NaN,15 miles,1C4JJXR61NW152861,"$68,218",Premier CDJR of Lamesa,"1611 Lubbock Hwy Lamesa, TX 79331","$67,935",...,8-Speed Automatic,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
528,NaN,Wrangler,NaN,NaN,---,1C4JJXR64NW108322,"$69,920",Shottenkirk Prosper Chrysler Dodge Jeep Ram,"2550 W University Dr Prosper, TX 75078","$69,920",...,8-Speed Automatic,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
530,NaN,Wrangler,NaN,NaN,3 miles,1C4JJXR6XNW108101,"$68,700",Pegasus CDJR,"305 South Interstate Highway 45 Ennis, TX 75119","$68,700",...,8-Speed Automatic,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
534,NaN,Wrangler,NaN,NaN,---,1C4JJXR62NW270773,"$70,475",Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018","$70,475",...,8-Speed Automatic,White (Alx9),20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
535,NaN,Wrangler,NaN,NaN,---,1C4JJXR61NW274197,"$70,870",Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018","$70,870",...,8-Speed Automatic,Gray (Alx9),20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1841,NaN,Tundra,NaN,NaN,5 miles,5TFPC5DB5NX004915,"$68,600",Gullo Toyota of Conroe,"500 I-45 South<br>Conroe, TX 77304","$68,600",...,Automatic,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,New,Large Crew Cab,NaN
1842,NaN,Tundra,NaN,NaN,10 miles,5TFMA5DB6NX034823,"$68,748",Sterling McCall Toyota Fort Bend,"20465 Southwest Freeway<br>Richmond, TX 77469","$68,748",...,Automatic,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,389 hp 3.5L V6,Four-Wheel Drive,Gasoline,New,Large Crew Cab,NaN
1843,NaN,Tundra,NaN,NaN,6 miles,5TFVC5DB5NX002511,"$78,001",Gullo Toyota of Conroe,"500 I-45 South<br>Conroe, TX 77304","$78,001",...,Automatic,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,New,Large Crew Cab,NaN
1844,NaN,Tundra,NaN,NaN,---,5TFVC5DB8NX002583,"$78,426",Mike Calvert Toyota,"2333 South Loop West<br>Houston, TX 77054","$78,426",...,Automatic,Black (Blk/Wht Semi-Aniline Lth),17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,New,Large Crew Cab,NaN
1845,NaN,Tundra,NaN,NaN,248 miles,5TFLA5DB1NX019691,"$78,990",Mike Calvert Toyota,"2333 South Loop West<br>Houston, TX 77054","$78,990",...,Automatic,Black,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,389 hp 3.5L V6,Four-Wheel Drive,Gasoline,New,"Large Crew Cab, Short Bed",NaN

In [42]:
all_scraping_data6 = all_scraping_data5.drop(columns=['Body type:'])
all_scraping_data6

,Make:,Model:,Year:,Mileage:,VIN:,Price:,Dealer Name:,Dealer Address:,Dealer's Price:,MSRP:,...,Transmission:,Interior Color:,Est. Gas Mileage*:,Battery Performance:,Engine:,Drivetrain:,Fuel Type:,Condition:,Cabin Size:,NHTSA Overall Safety Rating:
527,NaN,Wrangler,NaN,15 miles,1C4JJXR61NW152861,"$68,218",Premier CDJR of Lamesa,"1611 Lubbock Hwy Lamesa, TX 79331","$67,935","$67,935",...,8-Speed Automatic,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
528,NaN,Wrangler,NaN,---,1C4JJXR64NW108322,"$69,920",Shottenkirk Prosper Chrysler Dodge Jeep Ram,"2550 W University Dr Prosper, TX 75078","$69,920","$69,920",...,8-Speed Automatic,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
530,NaN,Wrangler,NaN,3 miles,1C4JJXR6XNW108101,"$68,700",Pegasus CDJR,"305 South Interstate Highway 45 Ennis, TX 75119","$68,700","$68,700",...,8-Speed Automatic,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
534,NaN,Wrangler,NaN,---,1C4JJXR62NW270773,"$70,475",Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018","$70,475","$70,475",...,8-Speed Automatic,White (Alx9),20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
535,NaN,Wrangler,NaN,---,1C4JJXR61NW274197,"$70,870",Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018","$70,870","$70,870",...,8-Speed Automatic,Gray (Alx9),20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1841,NaN,Tundra,NaN,5 miles,5TFPC5DB5NX004915,"$68,600",Gullo Toyota of Conroe,"500 I-45 South<br>Conroe, TX 77304","$68,600","$68,600",...,Automatic,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,New,Large Crew Cab,NaN
1842,NaN,Tundra,NaN,10 miles,5TFMA5DB6NX034823,"$68,748",Sterling McCall Toyota Fort Bend,"20465 Southwest Freeway<br>Richmond, TX 77469","$68,748","$67,253",...,Automatic,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,389 hp 3.5L V6,Four-Wheel Drive,Gasoline,New,Large Crew Cab,NaN
1843,NaN,Tundra,NaN,6 miles,5TFVC5DB5NX002511,"$78,001",Gullo Toyota of Conroe,"500 I-45 South<br>Conroe, TX 77304","$78,001","$78,001",...,Automatic,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,New,Large Crew Cab,NaN
1844,NaN,Tundra,NaN,---,5TFVC5DB8NX002583,"$78,426",Mike Calvert Toyota,"2333 South Loop West<br>Houston, TX 77054","$78,426","$78,426",...,Automatic,Black (Blk/Wht Semi-Aniline Lth),17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,New,Large Crew Cab,NaN
1845,NaN,Tundra,NaN,248 miles,5TFLA5DB1NX019691,"$78,990",Mike Calvert Toyota,"2333 South Loop West<br>Houston, TX 77054","$78,990",Not Provided,...,Automatic,Black,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,389 hp 3.5L V6,Four-Wheel Drive,Gasoline,New,"Large Crew Cab, Short Bed",NaN

In [43]:
all_scraping_data6.to_csv('../Resources/all_scraping_data3.csv', index=False)

In [56]:
#rename
all_scraping_data6.rename(columns = {'MSRP:':'MSRP',
                                       "Dealer's Price:":"Dealer's Price",
                                       'Price:':'Price',
                                       'Make:':'Make',
                                       'Model:':'Model',
                                       'Year:':'Year',
                                       'Transmission:':'Transmission',
                                       'Mileage:':'Mileage',
                                       'Dealer Name:':'Dealer Name',
                                       'Dealer Address:':'Dealer Address',
                                        'VIN:':'VIN Number'
                                        }, inplace = True)
all_scraping_data6

,Make,Model,Year,Mileage,VIN Number,Price,Dealer Name,Dealer Address,Dealer's Price,MSRP,...,Transmission,Interior Color:,Est. Gas Mileage*:,Battery Performance:,Engine:,Drivetrain:,Fuel Type:,Condition:,Cabin Size:,NHTSA Overall Safety Rating:
527,NaN,Wrangler,NaN,15 miles,1C4JJXR61NW152861,"$68,218",Premier CDJR of Lamesa,"1611 Lubbock Hwy Lamesa, TX 79331","$67,935","$67,935",...,8-Speed Automatic,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
528,NaN,Wrangler,NaN,---,1C4JJXR64NW108322,"$69,920",Shottenkirk Prosper Chrysler Dodge Jeep Ram,"2550 W University Dr Prosper, TX 75078","$69,920","$69,920",...,8-Speed Automatic,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
530,NaN,Wrangler,NaN,3 miles,1C4JJXR6XNW108101,"$68,700",Pegasus CDJR,"305 South Interstate Highway 45 Ennis, TX 75119","$68,700","$68,700",...,8-Speed Automatic,Black,20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
534,NaN,Wrangler,NaN,---,1C4JJXR62NW270773,"$70,475",Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018","$70,475","$70,475",...,8-Speed Automatic,White (Alx9),20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
535,NaN,Wrangler,NaN,---,1C4JJXR61NW274197,"$70,870",Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018","$70,870","$70,870",...,8-Speed Automatic,Gray (Alx9),20 MPG City\n20 MPG Highway\n20 MPG Combined,"2.4 hr charge time, 21 mi range",375 hp 2L I4,Four-Wheel Drive,Gasoline,New,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1841,NaN,Tundra,NaN,5 miles,5TFPC5DB5NX004915,"$68,600",Gullo Toyota of Conroe,"500 I-45 South<br>Conroe, TX 77304","$68,600","$68,600",...,Automatic,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,New,Large Crew Cab,NaN
1842,NaN,Tundra,NaN,10 miles,5TFMA5DB6NX034823,"$68,748",Sterling McCall Toyota Fort Bend,"20465 Southwest Freeway<br>Richmond, TX 77469","$68,748","$67,253",...,Automatic,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,389 hp 3.5L V6,Four-Wheel Drive,Gasoline,New,Large Crew Cab,NaN
1843,NaN,Tundra,NaN,6 miles,5TFVC5DB5NX002511,"$78,001",Gullo Toyota of Conroe,"500 I-45 South<br>Conroe, TX 77304","$78,001","$78,001",...,Automatic,NaN,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,New,Large Crew Cab,NaN
1844,NaN,Tundra,NaN,---,5TFVC5DB8NX002583,"$78,426",Mike Calvert Toyota,"2333 South Loop West<br>Houston, TX 77054","$78,426","$78,426",...,Automatic,Black (Blk/Wht Semi-Aniline Lth),17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,437 hp 3.5L V6 Hybrid,Four-Wheel Drive,Hybrid,New,Large Crew Cab,NaN
1845,NaN,Tundra,NaN,248 miles,5TFLA5DB1NX019691,"$78,990",Mike Calvert Toyota,"2333 South Loop West<br>Houston, TX 77054","$78,990",Not Provided,...,Automatic,Black,17 MPG City\n23 MPG Highway\n19 MPG Combined,NaN,389 hp 3.5L V6,Four-Wheel Drive,Gasoline,New,"Large Crew Cab, Short Bed",NaN

In [58]:
#reorder columns
all_scraping_data7 = all_scraping_data6[['VIN Number',
                                         'MSRP',
                                         "Dealer's Price",
                                         'Price',
                                         'Make',
                                         'Model',
                                         'Year',
                                         'Transmission',
                                         'Mileage',
                                         'Dealer Name',
                                         'Dealer Address',]]
all_scraping_data7

,VIN Number,MSRP,Dealer's Price,Price,Make,Model,Year,Transmission,Mileage,Dealer Name,Dealer Address
527,1C4JJXR61NW152861,"$67,935","$67,935","$68,218",NaN,Wrangler,NaN,8-Speed Automatic,15 miles,Premier CDJR of Lamesa,"1611 Lubbock Hwy Lamesa, TX 79331"
528,1C4JJXR64NW108322,"$69,920","$69,920","$69,920",NaN,Wrangler,NaN,8-Speed Automatic,---,Shottenkirk Prosper Chrysler Dodge Jeep Ram,"2550 W University Dr Prosper, TX 75078"
530,1C4JJXR6XNW108101,"$68,700","$68,700","$68,700",NaN,Wrangler,NaN,8-Speed Automatic,3 miles,Pegasus CDJR,"305 South Interstate Highway 45 Ennis, TX 75119"
534,1C4JJXR62NW270773,"$70,475","$70,475","$70,475",NaN,Wrangler,NaN,8-Speed Automatic,---,Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018"
535,1C4JJXR61NW274197,"$70,870","$70,870","$70,870",NaN,Wrangler,NaN,8-Speed Automatic,---,Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018"
...,...,...,...,...,...,...,...,...,...,...,...
1841,5TFPC5DB5NX004915,"$68,600","$68,600","$68,600",NaN,Tundra,NaN,Automatic,5 miles,Gullo Toyota of Conroe,"500 I-45 South<br>Conroe, TX 77304"
1842,5TFMA5DB6NX034823,"$67,253","$68,748","$68,748",NaN,Tundra,NaN,Automatic,10 miles,Sterling McCall Toyota Fort Bend,"20465 Southwest Freeway<br>Richmond, TX 77469"
1843,5TFVC5DB5NX002511,"$78,001","$78,001","$78,001",NaN,Tundra,NaN,Automatic,6 miles,Gullo Toyota of Conroe,"500 I-45 South<br>Conroe, TX 77304"
1844,5TFVC5DB8NX002583,"$78,426","$78,426","$78,426",NaN,Tundra,NaN,Automatic,---,Mike Calvert Toyota,"2333 South Loop West<br>Houston, TX 77054"
1845,5TFLA5DB1NX019691,Not Provided,"$78,990","$78,990",NaN,Tundra,NaN,Automatic,248 miles,Mike Calvert Toyota,"2333 South Loop West<br>Houston, TX 77054"

In [60]:
all_scraping_data7['Year'] = all_scraping_data7['Year'].fillna(2022)
all_scraping_data7

/var/folders/nk/670c2l4j02j1x3bk4kcm7qh80000gn/T/ipykernel_23333/111397104.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_scraping_data7['Year'] = all_scraping_data7['Year'].fillna(2022)

,VIN Number,MSRP,Dealer's Price,Price,Make,Model,Year,Transmission,Mileage,Dealer Name,Dealer Address
527,1C4JJXR61NW152861,"$67,935","$67,935","$68,218",NaN,Wrangler,2022.0,8-Speed Automatic,15 miles,Premier CDJR of Lamesa,"1611 Lubbock Hwy Lamesa, TX 79331"
528,1C4JJXR64NW108322,"$69,920","$69,920","$69,920",NaN,Wrangler,2022.0,8-Speed Automatic,---,Shottenkirk Prosper Chrysler Dodge Jeep Ram,"2550 W University Dr Prosper, TX 75078"
530,1C4JJXR6XNW108101,"$68,700","$68,700","$68,700",NaN,Wrangler,2022.0,8-Speed Automatic,3 miles,Pegasus CDJR,"305 South Interstate Highway 45 Ennis, TX 75119"
534,1C4JJXR62NW270773,"$70,475","$70,475","$70,475",NaN,Wrangler,2022.0,8-Speed Automatic,---,Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018"
535,1C4JJXR61NW274197,"$70,870","$70,870","$70,870",NaN,Wrangler,2022.0,8-Speed Automatic,---,Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018"
...,...,...,...,...,...,...,...,...,...,...,...
1841,5TFPC5DB5NX004915,"$68,600","$68,600","$68,600",NaN,Tundra,2022.0,Automatic,5 miles,Gullo Toyota of Conroe,"500 I-45 South<br>Conroe, TX 77304"
1842,5TFMA5DB6NX034823,"$67,253","$68,748","$68,748",NaN,Tundra,2022.0,Automatic,10 miles,Sterling McCall Toyota Fort Bend,"20465 Southwest Freeway<br>Richmond, TX 77469"
1843,5TFVC5DB5NX002511,"$78,001","$78,001","$78,001",NaN,Tundra,2022.0,Automatic,6 miles,Gullo Toyota of Conroe,"500 I-45 South<br>Conroe, TX 77304"
1844,5TFVC5DB8NX002583,"$78,426","$78,426","$78,426",NaN,Tundra,2022.0,Automatic,---,Mike Calvert Toyota,"2333 South Loop West<br>Houston, TX 77054"
1845,5TFLA5DB1NX019691,Not Provided,"$78,990","$78,990",NaN,Tundra,2022.0,Automatic,248 miles,Mike Calvert Toyota,"2333 South Loop West<br>Houston, TX 77054"

In [61]:
all_scraping_data7.to_csv('../Resources/all_scraping_data4.csv', index=False)

In [62]:
csv_file = '../Resources/all_scraping_data5.csv'
all_scraping_data8 = pd.read_csv(csv_file)
all_scraping_data8

,MSRP,Dealer's Price,Price,Make,Model,Year,Transmission,Mileage,Dealer Name,Dealer Address
0,"$67,935","$67,935","$68,218",Jeep,Wrangler,2022,8-Speed Automatic,15 miles,Premier CDJR of Lamesa,"1611 Lubbock Hwy Lamesa, TX 79331"
1,"$69,920","$69,920","$69,920",Jeep,Wrangler,2022,8-Speed Automatic,---,Shottenkirk Prosper Chrysler Dodge Jeep Ram,"2550 W University Dr Prosper, TX 75078"
2,"$68,700","$68,700","$68,700",Jeep,Wrangler,2022,8-Speed Automatic,3 miles,Pegasus CDJR,"305 South Interstate Highway 45 Ennis, TX 75119"
3,"$70,475","$70,475","$70,475",Jeep,Wrangler,2022,8-Speed Automatic,---,Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018"
4,"$70,870","$70,870","$70,870",Jeep,Wrangler,2022,8-Speed Automatic,---,Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018"
...,...,...,...,...,...,...,...,...,...,...
389,"$68,600","$68,600","$68,600",Toyota,Tundra,2022,Automatic,5 miles,Gullo Toyota of Conroe,"500 I-45 South<br>Conroe, TX 77304"
390,"$67,253","$68,748","$68,748",Toyota,Tundra,2022,Automatic,10 miles,Sterling McCall Toyota Fort Bend,"20465 Southwest Freeway<br>Richmond, TX 77469"
391,"$78,001","$78,001","$78,001",Toyota,Tundra,2022,Automatic,6 miles,Gullo Toyota of Conroe,"500 I-45 South<br>Conroe, TX 77304"
392,"$78,426","$78,426","$78,426",Toyota,Tundra,2022,Automatic,---,Mike Calvert Toyota,"2333 South Loop West<br>Houston, TX 77054"
393,Not Provided,"$78,990","$78,990",Toyota,Tundra,2022,Automatic,248 miles,Mike Calvert Toyota,"2333 South Loop West<br>Houston, TX 77054"

In [73]:
all_scraping_data8.to_csv('../Resources/all_scraping_data6.csv', index=False)

In [64]:
csv_file = '../Resources/all_scraping_data7.csv'
all_scraping_data9 = pd.read_csv(csv_file)
all_scraping_data9

,MSRP,Dealer's Price,Price,Make,Model,Year,Transmission,Mileage,Dealer Name,Dealer Address,Lat,Lng
0,"$67,935","$67,935","$68,218",Jeep,Wrangler,2022,8-Speed Automatic,15 miles,Premier CDJR of Lamesa,"1611 Lubbock Hwy Lamesa, TX 79331",32.747877,-101.950811
1,"$69,920","$69,920","$69,920",Jeep,Wrangler,2022,8-Speed Automatic,---,Shottenkirk Prosper Chrysler Dodge Jeep Ram,"2550 W University Dr Prosper, TX 75078",33.220389,-96.841397
2,"$68,700","$68,700","$68,700",Jeep,Wrangler,2022,8-Speed Automatic,3 miles,Pegasus CDJR,"305 South Interstate Highway 45 Ennis, TX 75119",32.331286,-96.615465
3,"$70,475","$70,475","$70,475",Jeep,Wrangler,2022,8-Speed Automatic,---,Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018",32.679079,-97.114775
4,"$70,870","$70,870","$70,870",Jeep,Wrangler,2022,8-Speed Automatic,---,Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018",32.679079,-97.114775
...,...,...,...,...,...,...,...,...,...,...,...,...
389,"$68,600","$68,600","$68,600",Toyota,Tundra,2022,Automatic,5 miles,Gullo Toyota of Conroe,"500 I-45 South, Conroe, TX 77304",30.300935,-95.468648
390,"$67,253","$68,748","$68,748",Toyota,Tundra,2022,Automatic,10 miles,Sterling McCall Toyota Fort Bend,"20465 Southwest Freeway, Richmond, TX 77469",29.558633,-95.694698
391,"$78,001","$78,001","$78,001",Toyota,Tundra,2022,Automatic,6 miles,Gullo Toyota of Conroe,"500 I-45 South, Conroe, TX 77304",30.300935,-95.468648
392,"$78,426","$78,426","$78,426",Toyota,Tundra,2022,Automatic,---,Mike Calvert Toyota,"2333 South Loop West, Houston, TX 77054",29.676139,-95.414021
393,Not Provided,"$78,990","$78,990",Toyota,Tundra,2022,Automatic,248 miles,Mike Calvert Toyota,"2333 South Loop West, Houston, TX 77054",29.676139,-95.414021

In [75]:
csv_file = '../Resources/All Scraping Data/all_scraping_data7.csv'
all_scraping_data20 = pd.read_csv(csv_file)
all_scraping_data20

,vin,msrp,dealer's price,price,make,model,year,transmission,mileage,dealer name,dealer address,lat,lng
0,1C4JJXR61NW152861,67935,67935,68218,Jeep,Wrangler,2022,8 Speed Automatic,15 miles,Premier CDJR of Lamesa,"1611 Lubbock Hwy Lamesa, TX 79331",32.747877,-101.950811
1,1C4JJXR64NW108322,69920,69920,69920,Jeep,Wrangler,2022,8 Speed Automatic,0 miles,Shottenkirk Prosper Chrysler Dodge Jeep Ram,"2550 W University Dr Prosper, TX 75078",33.220389,-96.841397
2,1C4JJXR6XNW108101,68700,68700,68700,Jeep,Wrangler,2022,8 Speed Automatic,3 miles,Pegasus CDJR,"305 South Interstate Highway 45 Ennis, TX 75119",32.331286,-96.615465
3,1C4JJXR62NW270773,70475,70475,70475,Jeep,Wrangler,2022,8 Speed Automatic,0 miles,Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018",32.679079,-97.114775
4,1C4JJXR61NW274197,70870,70870,70870,Jeep,Wrangler,2022,8 Speed Automatic,0 miles,Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018",32.679079,-97.114775
...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,5TFPC5DB5NX004915,68600,68600,68600,Toyota,Tundra,2022,Automatic,5 miles,Gullo Toyota of Conroe,"500 I-45 South, Conroe, TX 77304",30.300935,-95.468648
390,5TFMA5DB6NX034823,67253,68748,68748,Toyota,Tundra,2022,Automatic,10 miles,Sterling McCall Toyota Fort Bend,"20465 Southwest Freeway, Richmond, TX 77469",29.558633,-95.694698
391,5TFVC5DB5NX002511,78001,78001,78001,Toyota,Tundra,2022,Automatic,6 miles,Gullo Toyota of Conroe,"500 I-45 South, Conroe, TX 77304",30.300935,-95.468648
392,5TFVC5DB8NX002583,78426,78426,78426,Toyota,Tundra,2022,Automatic,0 miles,Mike Calvert Toyota,"2333 South Loop West, Houston, TX 77054",29.676139,-95.414021
393,5TFLA5DB1NX019691,78990,78990,78990,Toyota,Tundra,2022,Automatic,248 miles,Mike Calvert Toyota,"2333 South Loop West, Houston, TX 77054",29.676139,-95.414021

In [78]:
all_scraping_data21 = all_scraping_data20.drop_duplicates(subset=None, keep='first', inplace=False, ignore_index=False)
all_scraping_data21

,vin,msrp,dealer's price,price,make,model,year,transmission,mileage,dealer name,dealer address,lat,lng
0,1C4JJXR61NW152861,67935,67935,68218,Jeep,Wrangler,2022,8 Speed Automatic,15 miles,Premier CDJR of Lamesa,"1611 Lubbock Hwy Lamesa, TX 79331",32.747877,-101.950811
1,1C4JJXR64NW108322,69920,69920,69920,Jeep,Wrangler,2022,8 Speed Automatic,0 miles,Shottenkirk Prosper Chrysler Dodge Jeep Ram,"2550 W University Dr Prosper, TX 75078",33.220389,-96.841397
2,1C4JJXR6XNW108101,68700,68700,68700,Jeep,Wrangler,2022,8 Speed Automatic,3 miles,Pegasus CDJR,"305 South Interstate Highway 45 Ennis, TX 75119",32.331286,-96.615465
3,1C4JJXR62NW270773,70475,70475,70475,Jeep,Wrangler,2022,8 Speed Automatic,0 miles,Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018",32.679079,-97.114775
4,1C4JJXR61NW274197,70870,70870,70870,Jeep,Wrangler,2022,8 Speed Automatic,0 miles,Classic Chrysler Dodge Jeep Ram Fiat,"1111 E Interstate 20 Arlington, TX 76018",32.679079,-97.114775
...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,5TFPC5DB5NX004915,68600,68600,68600,Toyota,Tundra,2022,Automatic,5 miles,Gullo Toyota of Conroe,"500 I-45 South, Conroe, TX 77304",30.300935,-95.468648
390,5TFMA5DB6NX034823,67253,68748,68748,Toyota,Tundra,2022,Automatic,10 miles,Sterling McCall Toyota Fort Bend,"20465 Southwest Freeway, Richmond, TX 77469",29.558633,-95.694698
391,5TFVC5DB5NX002511,78001,78001,78001,Toyota,Tundra,2022,Automatic,6 miles,Gullo Toyota of Conroe,"500 I-45 South, Conroe, TX 77304",30.300935,-95.468648
392,5TFVC5DB8NX002583,78426,78426,78426,Toyota,Tundra,2022,Automatic,0 miles,Mike Calvert Toyota,"2333 South Loop West, Houston, TX 77054",29.676139,-95.414021
393,5TFLA5DB1NX019691,78990,78990,78990,Toyota,Tundra,2022,Automatic,248 miles,Mike Calvert Toyota,"2333 South Loop West, Houston, TX 77054",29.676139,-95.414021

In [79]:
len(all_scraping_data21)

389

In [80]:
all_scraping_data21.to_csv('../Resources/All Scraping Data/all_scraping_data7.csv', index=False)